remote_theme: pages-themes/hacker@v0.2.0
title: [BugBounty tips]
author: Boulanouar Rbih
description: [Tricks and tips for bug bounty hunting]
avatar: /images/favicon.png
social-network-links:
  email: "boulanouar.rbih@gmail.com"
  facebook: anoir.rebih
  github: rbih-boulanouar
  twitter: Buffer_0verflow
plugins:
  - jekyll-seo-tag
